#ifndef ETRADECLIENT_UTILITY_WIN_MSG_DEFINE_H_INCLUDED
#define ETRADECLIENT_UTILITY_WIN_MSG_DEFINE_H_INCLUDED

#include <windows.h>

#define WM_CEF_LOAD_START				(WM_USER + 100) // Start from 100.
#define WM_CEF_LOAD_END					(WM_USER + 101)
#define WM_CEF_TITLE_CHANGE				(WM_USER + 102)
#define WM_CEF_ADDRESS_CHANGE			(WM_USER + 103)
#define WM_CEF_STATE_CHANGE				(WM_USER + 104)
#define WM_CEF_STATUS_MESSAGE			(WM_USER + 105)
#define WM_CEF_NEW_WINDOW				(WM_USER + 106)
#define WM_CEF_WINDOW_CHECK				(WM_USER + 107)
#define WM_CEF_CLOSE_BROWSER			(WM_USER + 108)
#define WM_CEF_NEW_BROWSER				(WM_USER + 109)
#define WM_CEF_LOAD_ERROR				(WM_USER + 110)
#define WM_CEF_BEFORE_BROWSE			(WM_USER + 111)
#define WM_CEF_DOWNLOAD_UPDATE			(WM_USER + 112)
#define WM_CEF_SESSION_EXPIRED			(WM_USER + 113)
#define WM_CEF_AUTHENTICATE				(WM_USER + 114)
#define WM_CEF_BAD_CERTIFICATE			(WM_USER + 115)
#define WM_CEF_MSG_VIEW_NEW_BROWSER		(WM_USER + 116)
#define WM_CEF_MSG_VIEW_CLOSE_BROWSER	(WM_USER + 117)

#define WM_UPDATE_USER_MSG_COUNT		(WM_USER + 200)

#endif // ETRADECLIENT_UTILITY_WIN_MSG_DEFINE_H_INCLUDED
